<?php
// header("Access-Control-Allow-Origin: *");
// header("Content-Type: application/json; charset=UTF-8");

include './../base.php';
include './../includes/fpdf186/fpdf.php';

class PDF extends FPDF 
{ 
    // Page header 
    function Header() 
    { 
        global $project_name;

        $this->Image('./../asset/images/logo.png', 10, 6, 30);

        // Set font-family and font-size 
        $this->SetFont('Times','B',20); 

        // Move to the right 
        $this->Cell(80); 

        // Set the title of pages. 
        $this->Cell(30, 10, $project_name, 0, 2, 'C'); 

        $this->SetFont('Times','',10);
        // PUT TO RIGHT

        $this->Cell(52);
        $this->Cell(0, 11, 'Generated By: aceday', 0, 0);
        $this->Ln(5);

        $this->Cell(132);
        $this->Cell(0, 11, 'Start Date: 2025-03-01 00:00:00 AM', 0, 0);
        $this->Ln(5);

        $this->Cell(132);
        $this->Cell(0, 11, 'End Date: 2025-03-01 00:00:00 AM', 0, 0);
        // Break line with given space 
        $this->Ln(5); 

        $this->SetFont('Times','B',15);
        $this->Cell(0, 10, 'Generate Report', 0, 2, 'C');
    } 

    // Page footer 
    function Footer() 
    { 
        // Position at 1.5 cm from bottom 
        $this->SetY(-15); 
        
        // Set font-family and font-size of footer. 
        $this->SetFont('Arial', 'I', 8); 

        // set page number 
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C'); 
    } 
} 

// Create new object.

if ($_SERVER["REQUEST_METHOD"] == "GET") {
    global $conn;
    // $data = json_decode(file_get_contents("php://input"), true);

    // if (isset($data['datetime_start']) && isset($data['datetime_end'])) {
    //     $datetime_start = $data['datetime_start'];
    //     $datetime_end = $data['datetime_end'];
    // } else {
    //     echo json_encode(array(
    //         "status" => "error",
    //         "message" => "Please provide the start and end date."
    //     ));
    //     exit;
    // }

    // $datetime_start = date("Y-m-d h:i:s", strtotime($datetime_start));
    // $datetime_end = date("Y-m-d h:i:s", strtotime($datetime_end));

    $pdf = new PDF(); 
    $pdf->AliasNbPages(); 

    // Add new pages 
    $pdf->AddPage(); 

    // Set font-family and font-size. 
    $pdf->SetFont('Times','B',12); 

    // Loop to display line number content 
    // Header table
    $pdf->Cell(50, 10, 'Date Transaction', 1, 0, 'C');
    $pdf->Cell(50, 10, 'Name', 1, 0, 'C');
    $pdf->Cell(50, 10, 'Email', 1, 0, 'C');
    $pdf->Cell(40, 10, 'Payment', 1, 0, 'C');
    $pdf->Ln();

    $pdf->SetFont('Times','',12);

    // Import data
    $sql_cmd = "SELECT * FROM transactions";
    $stmt = $conn->prepare($sql_cmd);
    $stmt->execute();
    $result = $stmt->get_result();

    while ($row = $result->fetch_assoc()) {
        $pdf->Cell(50, 10, $row['date_transaction'], 1, 0, 'C');
        $pdf->Cell(50, 10, $row['name'], 1, 0, 'C');
        $pdf->Cell(50, 10, $row['email'], 1, 0, 'C');
        $pdf->Cell(40, 10, $row['payment'], 1, 0, 'C');
        $pdf->Ln();
    }

    $pdf->Output(); 
}
?>